// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSongURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSongURL'](arg1, arg2, arg3, arg4);
}

export function LoginByMobile(arg1, arg2) {
  return window['go']['main']['App']['LoginByMobile'](arg1, arg2);
}

export function LoginByToken(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoginByToken'](arg1, arg2, arg3, arg4);
}

export function SearchMusic(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchMusic'](arg1, arg2, arg3, arg4, arg5);
}

export function SendMobileCode(arg1) {
  return window['go']['main']['App']['SendMobileCode'](arg1);
}
